config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :graphs
  resources :votes, only: [:index, :create]
  resources :kilograms, only: [:index, :create]
  root to: 'graphs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graph.rb
class Graph < ApplicationRecord
end

app/models/kilogram.rb
class Kilogram < ApplicationRecord

  def self.lastone
    Kilogram.last
  end
end

app/models/vote.rb
class Vote < ApplicationRecord


  def self.totals
    [Vote.where(color: 'red').count, Vote.where(color: 'yellow').count]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def index
  end


end

app/controllers/kilograms_controller.rb
class KilogramsController < ApplicationController

  def index
    @kilograms = Kilogram.all
    @kilogram = Kilogram.new
    @last_kilo = Kilogram.lastone

    respond_to do |format|
      format.html
      format.json { render json: @kilograms }
    end

  end

  def create

    Kilogram.create(kg_params)
    @last_kilo = Kilogram.lastone
    respond_to do |format|
      format.js
    end
  end


  private

  def kg_params

    params.require(:kilogram).permit(:kg, :kg_date)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def index
    @votes = Vote.totals
    respond_to do |format|
      format.html
      format.json { render json: @votes }
    end
  end

  def create
    Vote.create(vote_params)
    @votes = Vote.totals
    respond_to do |format|
      format.js
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/kilograms_helper.rb
module KilogramsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/graphs/index.html.erb
<!DOCTYPE html>
 <html lang="en">
 <head>
   <meta charset="UTF-8">
   <title>graphs</title>

 </head>
 <body>
  <div class="title">
    <h1>Gráficos criados com D3.js</h1>
    <p>
      Diversos gráficos criados para o aprendizado da biblioteca D3.
    </p>
  </div>
  <div class="example"></div>

<!-- Script include in the page.
 d3 methods: scaleLinear (domain, range) / max / select (append, attr) / selectAll (data, enter (append, attr))
 append elements: svg in body / g in body (to move everything) / rect in svg /
 axis: append g to svg (canvas), translate and call(d3.axisBottom(widthScale))
-->
  <script>

    var dataArray = [10, 20, 40, 60];
    var width = 500;
    var height = 300;


    var widthScale = d3.scaleLinear()
                       .domain([0, + d3.max(dataArray)])
                       .range([0, width]);

    var color = d3.scaleLinear()
                  .domain([0, d3.max(dataArray)])
                  .range(["blue", "yellow"])


    var canvas = d3.select(".example")
                  .append("svg")
                  .attr("width", width + 20)
                  .attr("height", height)
                    .append("g")
                    .attr("transform", "translate(10, 10)")

    canvas.append("g")
          .attr("transform", "translate(0, 220)")
          .call(d3.axisBottom(widthScale).ticks(4));﻿

    var bars = canvas.selectAll("rect")
                .data(dataArray)
                .enter()
                    .append("rect")
                    .attr("width", function(d) { return widthScale(d); })
                    .attr("height", 50)
                    .attr("fill", function(d) { return color(d); })
                    .attr("y", function(d, i) { return i * 55; } );


  </script>
 </body>
 </html>

app/views/kilograms/create.js.erb
$(".kilos").html("<strong>Kilos:</strong> <%= @last_kilo.kg %>");
$(".data").html("<strong>Data:</strong> <%= @last_kilo.kg_date %>");

app/views/kilograms/index.html.erb
<h1>Pesate gordo!</h1>

<%= form_with(model: @kilogram) do |f| %>
  <%= f.text_field :kg %>
  <%= f.date_field :kg_date %>
  <%= f.submit %>

<% end %>

<% if @last_kilo %>
  <div class="kilograms">
    <p class="kilos"><strong>Kilos:</strong> <%= @last_kilo.kg %> kg</p>
    <p class="data"><strong>Fecha:</strong> <%= @last_kilo.kg_date %></p>
  </div>
<% end %>

<div class="kgGraph"></div>
<script>
  $(document).ready(function(){
  loadKilogramGraphic();
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraphicsProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/votes/create.js.erb
$("#red-count").html("<%= @votes[0] %>");
$("#yellow-count").html("<%= @votes[1] %>");
updateData();

app/views/votes/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>votes</title>
  </head>
  <body>
    <div class="main-container">
      <h1>Vermelho vs. Amarelo</h1>
      <div id="vote-counter">
        <h3>Contador</h3>
        <div >
          <p>Vermelho: <span id="red-count"><%= @votes[0] %></span></p>
          <p>Amarelo: <span id="yellow-count"><%= @votes[1] %></span></p>
        </div>
      </div>
      <div id="voting-box">
        <%= link_to 'Vota Vermelho', votes_path(vote: {color: 'red'}), {remote: true, method: :post, class: 'vote-button red' } %>
        <%= link_to 'Vote Amarelo', votes_path(vote: {color: 'yellow'}), {remote: true, method: :post, class: 'vote-button yellow' } %>
      </div>
      <div id="plot-container">

      </div>
    </div>

  </body>
</html>